// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

describe("Question 2", function() {

    it("should have a function experession named fibonacci()", function() {
        expect(typeof question2.fibonacci).toBe('function');
    });

    it("should not exceed four million", function() {
        expect(question2.range).toBe(4000000);
    });

    it("should only count against even values", function() {
        expect(question2.isEven(4)).toBe(true);
    });

    it("should return 44 when fibonacci(55) is called", function() {
        expect(question2.fibonacci(55)).toBe(44);
    });

    it("should return the sum of all even-valued numbers under four million", function() {
        expect(question2.fibonacci()).toBe(4613732);
    });
});